Profile Updates + Personalization on Patient Dashboard
Technical-Enablement-PingIdentity/BXHealth-Apps pull request #79
Opened 2021-12-09 21:22 UTC by kristinaasalgado

Just wanted to have this looked at sooner rather than later. 

There's some outstanding work to do around error handling for profile updates, but the core functionality works.
**Note:** I do have a hardcoded patient in there since the grab patientDN in NavBarMain 235 is not working right now.

Ended up keeping updating session variables to compare new, typed in values to because the data isn't sensitive and it was a long road ahead to get the form to work if I compared old state to new state in order to make the 5 profile network calls! Michael and I chatted about this and I feel ok about it.

2021-12-09 22:49 UTC, jon-oblander requested changes

2021-12-09 22:49 UTC, jon-oblander commented on bxhealth/src/pages/profile-settings/profile.js
> +      const [firstname, firstnameUpdated] = await this.updateUserProfileData(this.state.firstname, "firstName", "givenName");
curious why not a single update call?

2021-12-09 22:56 UTC, jon-oblander commented on bxhealth/src/pages/profile-settings/profile.js
> +  getUsername(patientDN) {
you can chain all these splits into a single line, make the code a bit more succinct.
getUsername should return a username rather than setting state.

2021-12-09 22:57 UTC, jon-oblander commented on bxhealth/src/pages/profile-settings/profile.js
> +    this.getUsername(patientDN);
see comment above. getUserName should return the username and this could be moved into the setState call above: line 134.  You 'could' remove getUserName altogether since only used in the 1 spot.

2021-12-09 22:58 UTC, jon-oblander requested changes
ok that should be it????

2021-12-09 23:58 UTC, kristinaasalgado commented on bxhealth/src/pages/profile-settings/profile.js
> +  getUsername(patientDN) {
Chained!

2021-12-09 23:59 UTC, kristinaasalgado commented on bxhealth/src/pages/profile-settings/profile.js
> +    this.getUsername(patientDN);
Removed altogether and just put it all in componentDidMount()

2021-12-10 00:02 UTC, kristinaasalgado commented on bxhealth/src/pages/profile-settings/profile.js
> +      const [firstname, firstnameUpdated] = await this.updateUserProfileData(this.state.firstname, "firstName", "givenName");
The PD patch call only takes in one attribute at a time/is atomic:
`{
    "modifications": [
        {
            "attributeName": "{{global.parameters.attributeName}}",
            "modificationType": "set",
            "values": "{{global.parameters.myValues}}"
        }
    ]
}`

So we can either have SingularKey send exactly that to it, orrrrrr we could hardcode the attributes that we're going to send in every time, but I didn't like the idea of hard coding those in case we add more attributes, etc. Does that make sense? That's why I have that like that (as annoying as it is). 

But if one fails, and others succeed, we end up throwing the error message anyways prompting the user to try again and double check their changes. Couldn't quite figure out how to line them up to wait for each other in a queue of sorts.

Let me know if you have more questions on that!

2021-12-10 00:34 UTC, jon-oblander approved these changes

2021-12-10 00:34 UTC, merged